[package]
name = "vx-tool-node"
version.workspace = true
edition.workspace = true
description = "Node.js tool support for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-core = { version = "0.4.0", path = "../../vx-core" }
vx-installer = { version = "0.4.0", path = "../../vx-installer", features = [
    "progress",
] }
vx-tool-standard = { version = "0.4.0", path = "../../vx-tool-standard" }
vx-plugin = { version = "0.4.0", path = "../../vx-plugin" }
vx-version = { version = "0.2.2", path = "../../vx-version" }
vx-tool-npm = { version = "0.4.0", path = "../vx-tool-npm" }
vx-config = { version = "0.4.1", path = "../../vx-config" }
vx-paths = { version = "0.3.1", path = "../../vx-paths" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
which = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
