[package]
name = "vx-tool-node"
version.workspace = true
edition.workspace = true
description = "Node.js tool support for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-core = { version = "0.1.36", path = "../../vx-core" }
vx-pm-npm = { version = "0.1.36", path = "../../vx-package-managers/vx-pm-npm" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
which = { workspace = true }
dirs = { workspace = true }
