[package]
name = "vx-tool-go"
version.workspace = true
edition.workspace = true
description = "Go tool support for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-core = { version = "0.3.0", path = "../../vx-core" }
vx-installer = { version = "0.3.0", path = "../../vx-installer" }
vx-tool-standard = { path = "../../vx-tool-standard" }
vx-plugin = { version = "0.3.0", path = "../../vx-plugin" }
vx-version = { version = "0.2.1", path = "../../vx-version" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
