# GoReleaser configuration for vx
# See: https://goreleaser.com

version: 2

project_name: vx

before:
  hooks:
    - rustup default stable
    - rustup component add rust-src

builds:
  - id: vx
    builder: rust
    binary: vx
    command: build
    targets:
      # Linux
      - x86_64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      # macOS
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      # Windows
      - x86_64-pc-windows-msvc
    flags:
      - --release
      - --package=vx
    env:
      - RUST_BACKTRACE=1
      - CARGO_BUILD_JOBS=1

archives:
  - id: default
    ids:
      - vx
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

# UPX compression for smaller binaries
upx:
  - ids: [vx]
    enabled: true
    compress: best
    lzma: false  # Disable LZMA for better compatibility
    brute: false  # Disable brute force for faster compression
    goos: [linux, windows, darwin]  # Compress for Linux, Windows, and macOS
    goarch: [amd64, arm64]  # Support both x64 and ARM64

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: loonghao
    name: vx
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## 🚀 vx {{ .Tag }} ({{ .Date }})

    Welcome to this new release of vx - Universal Development Tool Manager!

    ### ✨ What's New
    This release includes improvements and bug fixes to enhance your development experience.

    ### 📦 Download Options
    Choose the appropriate binary for your platform from the assets below.

  footer: |
    ## 🙏 Thanks!

    Those were the changes on {{ .Tag }}!

    **Made with ❤️ for developers, by developers**
  name_template: "{{.ProjectName}}-v{{.Version}}"

# Linux packages
nfpms:
  - id: packages
    package_name: vx
    vendor: Hal
    homepage: https://github.com/loonghao/vx
    maintainer: Hal <hal.long@outlook.com>
    description: Universal Development Tool Manager - Manage multiple development tools and their versions
    license: MIT
    formats:
      - deb      # Debian/Ubuntu only for now
    bindir: /usr/bin
    section: utils
    priority: optional
    dependencies:
      - git




# Package managers (disabled for testing)
# Scoop (Windows package manager)
# scoops:
#   - name: vx
#     repository:
#       owner: loonghao
#       name: scoop-bucket
#     homepage: https://github.com/loonghao/vx
#     description: Universal Development Tool Manager - Manage multiple development tools and their versions
#     license: MIT
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: "{{ .ProjectName }}: Update to {{ .Tag }}"

# AUR (Arch User Repository)
# aurs:
#   - name: vx-bin
#     homepage: https://github.com/loonghao/vx
#     description: Universal Development Tool Manager - Manage multiple development tools and their versions
#     maintainers:
#       - 'Hal <hal.long@outlook.com>'
#     license: MIT
#     private_key: '{{ .Env.AUR_KEY }}'
#     git_url: 'ssh://aur@aur.archlinux.org/vx-bin.git'
#     depends:
#       - git
#     optdepends:
#       - 'curl: for downloading tools'
#       - 'wget: alternative download method'
#     package: |-
#       # bin
#       install -Dm755 "./vx" "${pkgdir}/usr/bin/vx"
#
#       # license
#       install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/vx/LICENSE"
#
#       # documentation
#       install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/vx/README.md"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: 'updpkg: {{ .ProjectName }} {{ .Tag }}'
#     skip_upload: auto

# Docker images (disabled for testing)
# dockers:
#   - image_templates:
#       - "ghcr.io/loonghao/vx:{{ .Version }}-amd64"
#       - "ghcr.io/loonghao/vx:latest-amd64"
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"

# docker_manifests:
#   - name_template: "ghcr.io/loonghao/vx:{{ .Version }}"
#     image_templates:
#       - "ghcr.io/loonghao/vx:{{ .Version }}-amd64"

# Package managers (disabled for testing)
# Chocolatey (Windows package manager)
# chocolateys:
#   - name: vx
#     ids:
#       - default
#     owners: Hal
#     title: vx - Universal Development Tool Manager
#     authors: Hal <hal.long@outlook.com>
#     project_url: https://github.com/loonghao/vx
#     url_template: "https://github.com/loonghao/vx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     icon_url: "https://raw.githubusercontent.com/loonghao/vx/main/docs/logo.png"
#     copyright: 2025 Hal
#     license_url: https://github.com/loonghao/vx/blob/main/LICENSE
#     require_license_acceptance: false
#     project_source_url: https://github.com/loonghao/vx
#     docs_url: https://github.com/loonghao/vx/blob/main/README.md
#     bug_tracker_url: https://github.com/loonghao/vx/issues
#     tags: "development tools version manager cli rust"
#     summary: Universal Development Tool Manager - Manage multiple development tools and their versions
#     description: |
#       vx is a universal development tool manager that helps developers manage multiple tools and their versions.
#       It supports automatic installation, version switching, and environment isolation for various development tools.
#     release_notes: "https://github.com/loonghao/vx/releases/tag/v{{ .Version }}"
#     dependencies:
#       - id: git
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#     source_repo: "https://push.chocolatey.org/"
#     skip_publish: false

# Winget (Windows Package Manager)
# winget:
#   - name: vx
#     publisher: Hal
#     short_description: "Universal Development Tool Manager"
#     license: "mit"
#     publisher_url: https://github.com/loonghao/vx
#     publisher_support_url: "https://github.com/loonghao/vx/issues/new"
#     package_identifier: Hal.vx
#     ids:
#       - default
#     url_template: "https://github.com/loonghao/vx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"
#     homepage: "https://github.com/loonghao/vx"
#     description: "vx is a universal development tool manager that helps developers manage multiple tools and their versions with automatic installation, version switching, and environment isolation."
#     license_url: "https://github.com/loonghao/vx/blob/main/LICENSE"
#     copyright: "2025 Hal"
#     skip_upload: auto
#     release_notes: "{{.Changelog}}"
#     tags:
#       - development
#       - tools
#       - version-manager
#       - cli
#       - rust
#     dependencies:
#       - package_identifier: Git.Git
#         minimum_version: 2.0.0
#     repository:
#       owner: microsoft
#       name: winget-pkgs
#       branch: "vx-{{.Version}}"
#       pull_request:
#         enabled: true
#         draft: false
#         base:
#           owner: microsoft
#           name: winget-pkgs
#           branch: master

# Announce
announce:
  skip: '{{gt .Patch 0}}'
