name: 'Setup vx'
description: 'Setup vx - Universal Development Tool Manager for your CI/CD workflows'
author: 'loonghao'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  version:
    description: 'vx version to install (e.g., "0.5.7", "latest")'
    required: false
    default: 'latest'
  github-token:
    description: 'GitHub token for API requests (avoids rate limiting)'
    required: false
    default: ${{ github.token }}
  tools:
    description: 'Space-separated list of tools to pre-install (e.g., "node go uv")'
    required: false
    default: ''
  cache:
    description: 'Enable caching of vx tools directory'
    required: false
    default: 'true'
  cache-key-prefix:
    description: 'Custom prefix for cache key'
    required: false
    default: 'vx-tools'

outputs:
  version:
    description: 'The installed vx version'
    value: ${{ steps.setup.outputs.version }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    # Cache vx tools directory
    - name: Cache vx tools
      if: inputs.cache == 'true'
      id: cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.vx
          ~/.local/bin/vx
          ~/.local/bin/vx.exe
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ inputs.version }}-${{ inputs.tools }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ inputs.version }}-
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    # Install vx on Linux/macOS
    - name: Install vx (Unix)
      if: runner.os != 'Windows'
      id: install-unix
      shell: bash
      env:
        VX_VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -e

        INSTALL_DIR="$HOME/.local/bin"
        mkdir -p "$INSTALL_DIR"

        # Add to PATH immediately for current step and subsequent steps
        echo "$INSTALL_DIR" >> $GITHUB_PATH
        export PATH="$INSTALL_DIR:$PATH"

        # Add vx managed tools bin directory to PATH
        # This allows tools installed by vx (like uv, node, etc.) to be found
        VX_BIN_DIR="$HOME/.vx/bin"
        mkdir -p "$VX_BIN_DIR"
        echo "$VX_BIN_DIR" >> $GITHUB_PATH
        export PATH="$VX_BIN_DIR:$PATH"

        # Skip download if already cached
        if [ -f "$INSTALL_DIR/vx" ]; then
          echo "vx already installed (from cache)"
        else
          echo "Installing vx..."

          # Determine version
          if [ "$VX_VERSION" = "latest" ]; then
            echo "Fetching latest version..."
            # Retry logic for API requests
            for i in 1 2 3; do
              TAG_NAME=$(curl -sS --retry 3 --retry-delay 2 -H "Authorization: Bearer $GH_TOKEN" \
                "https://api.github.com/repos/loonghao/vx/releases/latest" | \
                grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
              if [ -n "$TAG_NAME" ]; then
                break
              fi
              echo "Retry $i: Failed to fetch latest version..."
              sleep 2
            done
            if [ -z "$TAG_NAME" ]; then
              echo "Failed to fetch latest version after 3 retries"
              exit 1
            fi
          else
            # Handle version format
            if [[ "$VX_VERSION" =~ ^vx-v ]]; then
              TAG_NAME="$VX_VERSION"
            elif [[ "$VX_VERSION" =~ ^v ]]; then
              TAG_NAME="vx-$VX_VERSION"
            else
              TAG_NAME="vx-v$VX_VERSION"
            fi
          fi

          echo "Installing vx $TAG_NAME..."

          # Detect platform
          OS=$(uname -s)
          ARCH=$(uname -m)

          case "$OS" in
            Linux)
              case "$ARCH" in
                x86_64)  TARGET="x86_64-unknown-linux-musl" ;;
                aarch64) TARGET="aarch64-unknown-linux-musl" ;;
                *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              ;;
            Darwin)
              case "$ARCH" in
                x86_64)  TARGET="x86_64-apple-darwin" ;;
                arm64)   TARGET="aarch64-apple-darwin" ;;
                *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              ;;
            *)
              echo "Unsupported OS: $OS"
              exit 1
              ;;
          esac

          ARCHIVE_NAME="vx-${TARGET}.tar.gz"
          DOWNLOAD_URL="https://github.com/loonghao/vx/releases/download/${TAG_NAME}/${ARCHIVE_NAME}"

          echo "Downloading from: $DOWNLOAD_URL"

          # Download with authentication and retry
          TEMP_DIR=$(mktemp -d)
          trap 'rm -rf "$TEMP_DIR"' EXIT

          curl -fsSL --retry 3 --retry-delay 2 --retry-all-errors \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/octet-stream" \
            "$DOWNLOAD_URL" -o "$TEMP_DIR/$ARCHIVE_NAME"

          # Extract
          tar -xzf "$TEMP_DIR/$ARCHIVE_NAME" -C "$TEMP_DIR"

          # Find and install binary
          BINARY_PATH=$(find "$TEMP_DIR" -name "vx" -type f | head -n1)
          if [ -z "$BINARY_PATH" ]; then
            echo "vx binary not found in archive"
            exit 1
          fi

          cp "$BINARY_PATH" "$INSTALL_DIR/vx"
          chmod +x "$INSTALL_DIR/vx"

          echo "vx installed to $INSTALL_DIR/vx"
        fi

        # Verify installation using full path (PATH update via GITHUB_PATH only affects subsequent steps)
        "$INSTALL_DIR/vx" --version

        # Export install dir for subsequent steps
        echo "VX_INSTALL_DIR=$INSTALL_DIR" >> $GITHUB_ENV

    # Install vx on Windows
    - name: Install vx (Windows)
      if: runner.os == 'Windows'
      id: install-windows
      shell: pwsh
      env:
        VX_VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        $ErrorActionPreference = "Stop"

        $InstallDir = "$env:USERPROFILE\.local\bin"
        New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

        # Add to PATH immediately for current step and subsequent steps
        $InstallDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "$InstallDir;$env:PATH"

        # Add vx managed tools bin directory to PATH
        # This allows tools installed by vx (like uv, node, etc.) to be found
        $VxBinDir = "$env:USERPROFILE\.vx\bin"
        New-Item -ItemType Directory -Path $VxBinDir -Force | Out-Null
        $VxBinDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "$VxBinDir;$env:PATH"

        $vxPath = "$InstallDir\vx.exe"

        # Skip download if already cached
        if (Test-Path $vxPath) {
          Write-Host "vx already installed (from cache)"
        } else {
          Write-Host "Installing vx..."

          # Determine version with retry
          $maxRetries = 3
          $TagName = $null

          if ($env:VX_VERSION -eq "latest") {
            Write-Host "Fetching latest version..."
            $headers = @{ "Authorization" = "Bearer $env:GH_TOKEN" }

            for ($i = 1; $i -le $maxRetries; $i++) {
              try {
                $response = Invoke-RestMethod -Uri "https://api.github.com/repos/loonghao/vx/releases/latest" -Headers $headers -TimeoutSec 30
                $TagName = $response.tag_name
                if ($TagName) { break }
              } catch {
                Write-Host "Retry $i`: Failed to fetch latest version: $_"
                if ($i -lt $maxRetries) { Start-Sleep -Seconds 2 }
              }
            }

            if (-not $TagName) {
              Write-Error "Failed to fetch latest version after $maxRetries retries"
              exit 1
            }
          } else {
            if ($env:VX_VERSION -match '^vx-v') {
              $TagName = $env:VX_VERSION
            } elseif ($env:VX_VERSION -match '^v') {
              $TagName = "vx-$env:VX_VERSION"
            } else {
              $TagName = "vx-v$env:VX_VERSION"
            }
          }

          Write-Host "Installing vx $TagName..."

          # Detect architecture
          $arch = if ([Environment]::Is64BitOperatingSystem) { "x86_64" } else { "i686" }
          $Target = "$arch-pc-windows-msvc"
          $ArchiveName = "vx-$Target.zip"
          $DownloadUrl = "https://github.com/loonghao/vx/releases/download/$TagName/$ArchiveName"

          Write-Host "Downloading from: $DownloadUrl"

          # Download with authentication and retry
          $TempDir = New-TemporaryFile | ForEach-Object { Remove-Item $_; New-Item -ItemType Directory -Path $_ }
          $ArchivePath = Join-Path $TempDir $ArchiveName

          $headers = @{
            "Authorization" = "Bearer $env:GH_TOKEN"
            "Accept" = "application/octet-stream"
          }

          $downloadSuccess = $false
          for ($i = 1; $i -le $maxRetries; $i++) {
            try {
              Invoke-WebRequest -Uri $DownloadUrl -OutFile $ArchivePath -Headers $headers -TimeoutSec 120
              if ((Test-Path $ArchivePath) -and ((Get-Item $ArchivePath).Length -gt 1024)) {
                $downloadSuccess = $true
                break
              }
            } catch {
              Write-Host "Retry $i`: Download failed: $_"
              Remove-Item $ArchivePath -Force -ErrorAction SilentlyContinue
              if ($i -lt $maxRetries) { Start-Sleep -Seconds 2 }
            }
          }

          if (-not $downloadSuccess) {
            Write-Error "Failed to download vx after $maxRetries retries"
            exit 1
          }

          # Extract
          Expand-Archive -Path $ArchivePath -DestinationPath $TempDir -Force

          # Find and install binary
          $BinaryPath = Get-ChildItem -Path $TempDir -Name "vx.exe" -Recurse | Select-Object -First 1
          if (-not $BinaryPath) {
            Write-Error "vx.exe not found in archive"
            exit 1
          }

          Copy-Item -Path (Join-Path $TempDir $BinaryPath) -Destination $vxPath -Force

          # Cleanup
          Remove-Item -Path $TempDir -Recurse -Force -ErrorAction SilentlyContinue

          Write-Host "vx installed to $vxPath"
        }

        # Verify installation using full path (PATH update via GITHUB_PATH only affects subsequent steps)
        & $vxPath --version

        # Export install dir for subsequent steps
        "VX_INSTALL_DIR=$InstallDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # Get installed version
    - name: Get vx version
      id: setup
      shell: bash
      run: |
        # Ensure PATH includes vx install directory (in case GITHUB_PATH hasn't taken effect yet)
        if [ -n "$VX_INSTALL_DIR" ]; then
          export PATH="$VX_INSTALL_DIR:$PATH"
        fi

        # Fallback: check common install locations
        if ! command -v vx &> /dev/null; then
          if [ -f "$HOME/.local/bin/vx" ]; then
            export PATH="$HOME/.local/bin:$PATH"
          fi
        fi

        # Add vx managed tools to PATH
        export PATH="$HOME/.vx/bin:$PATH"

        VERSION=$(vx --version | head -1 | awk '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "vx version: $VERSION"

    # Pre-install specified tools
    - name: Pre-install tools
      if: inputs.tools != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Ensure PATH includes vx install directory
        if [ -n "$VX_INSTALL_DIR" ]; then
          export PATH="$VX_INSTALL_DIR:$PATH"
        fi

        # Fallback: check common install locations
        if ! command -v vx &> /dev/null; then
          if [ -f "$HOME/.local/bin/vx" ]; then
            export PATH="$HOME/.local/bin:$PATH"
          fi
        fi

        # Add vx managed tools to PATH
        export PATH="$HOME/.vx/bin:$PATH"

        echo "Pre-installing tools: ${{ inputs.tools }}"
        for tool in ${{ inputs.tools }}; do
          echo "Installing $tool..."
          vx $tool --version || echo "Warning: Failed to install $tool"
        done

        # Show installed tools
        echo ""
        echo "Installed tools:"
        vx list --status

    # Setup environment for .vx.toml projects
    # This step exports tool paths to GITHUB_PATH so subsequent steps can use them
    - name: Setup vx environment
      shell: bash
      run: |
        # Ensure PATH includes vx install directory
        if [ -n "$VX_INSTALL_DIR" ]; then
          export PATH="$VX_INSTALL_DIR:$PATH"
        fi
        if [ -f "$HOME/.local/bin/vx" ]; then
          export PATH="$HOME/.local/bin:$PATH"
        fi

        # Check if .vx.toml exists in the current directory
        if [ -f ".vx.toml" ]; then
          echo "Found .vx.toml, exporting tool paths..."

          # Use vx env export to get the paths and add them to GITHUB_PATH
          # This ensures tools installed by vx setup are available in subsequent steps
          eval "$(vx env export --format shell 2>/dev/null || true)"

          # Also add paths to GITHUB_PATH for subsequent steps
          vx env export --format github 2>/dev/null | grep -E '^echo.*GITHUB_PATH' | while read -r line; do
            # Extract the path from the echo command
            path=$(echo "$line" | sed 's/echo "\(.*\)" >> \$GITHUB_PATH/\1/')
            if [ -n "$path" ] && [ -d "$path" ]; then
              echo "$path" >> $GITHUB_PATH
            fi
          done || true
        fi
