name: 'Setup vx'
description: 'Setup vx - Universal Development Tool Manager for your CI/CD workflows'
author: 'loonghao'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  version:
    description: 'vx version to install (e.g., "0.5.7", "latest")'
    required: false
    default: 'latest'
  github-token:
    description: 'GitHub token for API requests (avoids rate limiting)'
    required: false
    default: ${{ github.token }}
  tools:
    description: 'Space-separated list of tools to pre-install (e.g., "node go uv")'
    required: false
    default: ''
  cache:
    description: 'Enable caching of vx tools directory'
    required: false
    default: 'true'
  cache-key-prefix:
    description: 'Custom prefix for cache key'
    required: false
    default: 'vx-tools'

outputs:
  version:
    description: 'The installed vx version'
    value: ${{ steps.setup.outputs.version }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    # Cache vx tools directory
    - name: Cache vx tools
      if: inputs.cache == 'true'
      id: cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.vx
          ~/.local/bin/vx
          ~/.local/bin/vx.exe
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ inputs.version }}-${{ inputs.tools }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ inputs.version }}-
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    # Install vx on Linux/macOS
    - name: Install vx (Unix)
      if: runner.os != 'Windows'
      id: install-unix
      shell: bash
      env:
        VX_VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -e

        INSTALL_DIR="$HOME/.local/bin"
        mkdir -p "$INSTALL_DIR"

        # Skip download if already cached
        if [ -f "$INSTALL_DIR/vx" ]; then
          echo "vx already installed (from cache)"
        else
          echo "Installing vx..."

          # Determine version
          if [ "$VX_VERSION" = "latest" ]; then
            echo "Fetching latest version..."
            TAG_NAME=$(curl -sS -H "Authorization: Bearer $GH_TOKEN" \
              "https://api.github.com/repos/loonghao/vx/releases/latest" | \
              grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          else
            # Handle version format
            if [[ "$VX_VERSION" =~ ^vx-v ]]; then
              TAG_NAME="$VX_VERSION"
            elif [[ "$VX_VERSION" =~ ^v ]]; then
              TAG_NAME="vx-$VX_VERSION"
            else
              TAG_NAME="vx-v$VX_VERSION"
            fi
          fi

          echo "Installing vx $TAG_NAME..."

          # Detect platform
          OS=$(uname -s)
          ARCH=$(uname -m)

          case "$OS" in
            Linux)
              case "$ARCH" in
                x86_64)  TARGET="x86_64-unknown-linux-musl" ;;
                aarch64) TARGET="aarch64-unknown-linux-musl" ;;
                *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              ;;
            Darwin)
              case "$ARCH" in
                x86_64)  TARGET="x86_64-apple-darwin" ;;
                arm64)   TARGET="aarch64-apple-darwin" ;;
                *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              ;;
            *)
              echo "Unsupported OS: $OS"
              exit 1
              ;;
          esac

          ARCHIVE_NAME="vx-${TARGET}.tar.gz"
          DOWNLOAD_URL="https://github.com/loonghao/vx/releases/download/${TAG_NAME}/${ARCHIVE_NAME}"

          echo "Downloading from: $DOWNLOAD_URL"

          # Download with authentication
          TEMP_DIR=$(mktemp -d)
          trap 'rm -rf "$TEMP_DIR"' EXIT

          curl -fsSL -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/octet-stream" \
            "$DOWNLOAD_URL" -o "$TEMP_DIR/$ARCHIVE_NAME"

          # Extract
          tar -xzf "$TEMP_DIR/$ARCHIVE_NAME" -C "$TEMP_DIR"

          # Find and install binary
          BINARY_PATH=$(find "$TEMP_DIR" -name "vx" -type f | head -n1)
          if [ -z "$BINARY_PATH" ]; then
            echo "vx binary not found in archive"
            exit 1
          fi

          cp "$BINARY_PATH" "$INSTALL_DIR/vx"
          chmod +x "$INSTALL_DIR/vx"

          echo "vx installed to $INSTALL_DIR/vx"
        fi

        # Add to PATH
        echo "$INSTALL_DIR" >> $GITHUB_PATH

        # Verify installation
        "$INSTALL_DIR/vx" --version

    # Install vx on Windows
    - name: Install vx (Windows)
      if: runner.os == 'Windows'
      id: install-windows
      shell: pwsh
      env:
        VX_VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        $ErrorActionPreference = "Stop"

        $InstallDir = "$env:USERPROFILE\.local\bin"
        New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

        $vxPath = "$InstallDir\vx.exe"

        # Skip download if already cached
        if (Test-Path $vxPath) {
          Write-Host "vx already installed (from cache)"
        } else {
          Write-Host "Installing vx..."

          # Determine version
          if ($env:VX_VERSION -eq "latest") {
            Write-Host "Fetching latest version..."
            $headers = @{ "Authorization" = "Bearer $env:GH_TOKEN" }
            $response = Invoke-RestMethod -Uri "https://api.github.com/repos/loonghao/vx/releases/latest" -Headers $headers
            $TagName = $response.tag_name
          } else {
            if ($env:VX_VERSION -match '^vx-v') {
              $TagName = $env:VX_VERSION
            } elseif ($env:VX_VERSION -match '^v') {
              $TagName = "vx-$env:VX_VERSION"
            } else {
              $TagName = "vx-v$env:VX_VERSION"
            }
          }

          Write-Host "Installing vx $TagName..."

          # Detect architecture
          $arch = if ([Environment]::Is64BitOperatingSystem) { "x86_64" } else { "i686" }
          $Target = "$arch-pc-windows-msvc"
          $ArchiveName = "vx-$Target.zip"
          $DownloadUrl = "https://github.com/loonghao/vx/releases/download/$TagName/$ArchiveName"

          Write-Host "Downloading from: $DownloadUrl"

          # Download with authentication
          $TempDir = New-TemporaryFile | ForEach-Object { Remove-Item $_; New-Item -ItemType Directory -Path $_ }
          $ArchivePath = Join-Path $TempDir $ArchiveName

          $headers = @{
            "Authorization" = "Bearer $env:GH_TOKEN"
            "Accept" = "application/octet-stream"
          }
          Invoke-WebRequest -Uri $DownloadUrl -OutFile $ArchivePath -Headers $headers

          # Extract
          Expand-Archive -Path $ArchivePath -DestinationPath $TempDir -Force

          # Find and install binary
          $BinaryPath = Get-ChildItem -Path $TempDir -Name "vx.exe" -Recurse | Select-Object -First 1
          if (-not $BinaryPath) {
            Write-Error "vx.exe not found in archive"
            exit 1
          }

          Copy-Item -Path (Join-Path $TempDir $BinaryPath) -Destination $vxPath -Force

          # Cleanup
          Remove-Item -Path $TempDir -Recurse -Force -ErrorAction SilentlyContinue

          Write-Host "vx installed to $vxPath"
        }

        # Add to PATH
        $InstallDir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Verify installation
        & $vxPath --version

    # Get installed version
    - name: Get vx version
      id: setup
      shell: bash
      run: |
        VERSION=$(vx --version | head -1 | awk '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "vx version: $VERSION"

    # Pre-install specified tools
    - name: Pre-install tools
      if: inputs.tools != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Pre-installing tools: ${{ inputs.tools }}"
        for tool in ${{ inputs.tools }}; do
          echo "Installing $tool..."
          vx $tool --version || echo "Warning: Failed to install $tool"
        done

        # Show installed tools
        echo ""
        echo "Installed tools:"
        vx list --status
