doc-valid-idents = [
  "vx",
  "CLI",
  "API",
  "JSON",
  "YAML",
  "TOML",
  "URL",
  "HTTP",
  "HTTPS",
  ".." # Include the defaults
]

# Disable pedantic lints that are too noisy for this project
avoid-breaking-exported-api = false
too-many-lines-threshold = 150
