coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        # Only warn, don't fail CI
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        # Only warn, don't fail CI
        informational: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "examples/"
  - "target/"
  - "scripts/"
