//! Provider registry setup and management
//!
//! This module provides the registry setup for all providers.
//! All providers are loaded from `provider.star` files (RFC-0037).
//! Static Rust providers are registered directly into the ProviderRegistry.

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Arc, OnceLock};
use tracing::trace;
use vx_paths::{PROJECT_VX_DIR, VxPaths, find_project_root};
use vx_runtime::{
    ConstraintRule, DependencyConstraint, ManifestVersionPattern, Provider, ProviderRegistry,
    Runtime, RuntimeContext, init_constraints_from_star,
};
use vx_runtime_http::create_runtime_context;
use vx_starlark::provider::types::PackageAlias;
use vx_starlark::{StarMetadata, StarlarkEngine};
use vx_versions::{RangeOp, VersionConstraint, VersionRequest};

// ---------------------------------------------------------------------------
// Compile-time embedded provider.star contents (RFC-0037)
//
// build.rs writes provider_stars.rs:
//   - PROVIDER_STAR_<NAME> : &str  (individual star content, via include_str!)
//   - ALL_PROVIDER_STARS   : &[(&str, &str)]  (name, star_content pairs)
// ---------------------------------------------------------------------------
include!(concat!(env!("OUT_DIR"), "/provider_stars.rs"));

// Include the compile-time generated embedded bridge binaries
mod embedded_bridges {
    include!(concat!(env!("OUT_DIR"), "/embedded_bridges.rs"));
}

static PROVIDER_HANDLES_INIT: tokio::sync::OnceCell<()> = tokio::sync::OnceCell::const_new();
static CONSTRAINTS_INIT: OnceLock<()> = OnceLock::new();

/// Register embedded bridge binaries into the global bridge registry.
/// This must be called early in startup, before any provider attempts to deploy bridges.
pub fn register_embedded_bridges() {
    vx_bridge::register_embedded_bridge("MSBuild", embedded_bridges::MSBUILD_BRIDGE_BYTES);
}

// All builtin providers are registered automatically from ALL_PROVIDER_STARS,
// which is generated by build.rs at compile time by scanning the vx-providers/
// directory. No manual list is needed — adding a provider.star file is enough.

/// Create and initialize the provider registry with all available providers.
///
/// Uses static registration for Rust-implemented providers.
/// `provider.star` files are loaded separately via `init_provider_handles()`.
pub fn create_registry() -> ProviderRegistry {
    create_static_registry()
}

/// Build a registry using static registration only.
///
/// All builtin providers are loaded from `ALL_PROVIDER_STARS`, which is
/// generated at compile time by `build.rs` scanning the `vx-providers/`
/// directory. Any provider name is supported — no Rust identifier constraints.
fn create_static_registry() -> ProviderRegistry {
    let registry = ProviderRegistry::new();

    // Register all builtin providers lazily from the compile-time generated array.
    // build.rs scans vx-providers/*/provider.star and embeds them all here.
    // Providers are only materialized when a runtime is actually requested.
    for (name, star_content) in ALL_PROVIDER_STARS {
        register_builtin_provider_lazy(&registry, name, star_content);
    }

    // User / project-level providers added via `vx provider add`
    for (name, star_content) in load_star_overrides() {
        register_dynamic_provider_lazy(&registry, name, star_content);
    }

    registry
}

fn register_builtin_provider_lazy(
    registry: &ProviderRegistry,
    name: &'static str,
    star_content: &'static str,
) {
    let runtime_names = extract_runtime_lookup_names(name, star_content);
    registry.register_lazy(
        name.to_string(),
        runtime_names,
        Box::new(move || vx_starlark::create_provider(name, star_content)),
    );
}

fn register_dynamic_provider_lazy(registry: &ProviderRegistry, name: String, star_content: String) {
    let runtime_names = extract_runtime_lookup_names(&name, &star_content);
    let provider_name = name.clone();

    registry.register_lazy(
        provider_name,
        runtime_names,
        Box::new(move || vx_starlark::create_provider(&name, &star_content)),
    );
}

fn extract_runtime_lookup_names(provider_name: &str, star_content: &str) -> Vec<String> {
    let meta = StarMetadata::parse(star_content);
    let mut names = Vec::new();

    for runtime in meta.runtimes {
        if let Some(name) = runtime.name {
            names.push(name);
        }
        names.extend(runtime.aliases);
    }

    if names.is_empty() {
        names.push(provider_name.to_string());
    }

    names.sort();
    names.dedup();
    names
}

/// Load user and project-level `provider.star` overrides.
///
/// Returns a list of `(name, star_content)` pairs from:
/// 1. `~/.vx/providers/*/provider.star` (user-level)
/// 2. `<project>/.vx/providers/*/provider.star` (project-level)
pub fn load_star_overrides() -> Vec<(String, String)> {
    let mut overrides = Vec::new();

    // User-level: ~/.vx/providers
    if let Ok(paths) = VxPaths::new() {
        let user_dir = paths.base_dir.join("providers");
        collect_star_files(&user_dir, &mut overrides);
    }

    // Project-level: <project>/.vx/providers
    if let Ok(cwd) = std::env::current_dir()
        && let Some(project_root) = find_project_root(&cwd)
    {
        let project_dir = project_root.join(PROJECT_VX_DIR).join("providers");
        collect_star_files(&project_dir, &mut overrides);
    }

    overrides
}

fn collect_star_files(dir: &std::path::Path, out: &mut Vec<(String, String)>) {
    if !dir.exists() {
        return;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let star_path = entry.path().join("provider.star");
        if star_path.exists()
            && let Ok(content) = std::fs::read_to_string(&star_path)
        {
            let name = entry.file_name().to_string_lossy().to_string();
            out.push((name, content));
        }
    }
}

/// Initialize the global ProviderHandle registry with all built-in providers (RFC-0037)
///
/// This function registers all embedded `provider.star` files into the
/// `global_registry()` so that CLI commands can use `ProviderHandle` for
/// path queries, version management, and post-install operations.
///
/// Also loads user-level (`~/.vx/providers/*/provider.star`) and
/// project-level (`.vx/providers/*/provider.star`) overrides so that
/// providers added via `vx provider add` are immediately available.
///
/// Should be called once at CLI startup, before any command is dispatched.
async fn init_provider_handles_inner() {
    use vx_starlark::handle::global_registry_mut;

    let mut reg = global_registry_mut().await;

    // 1. Built-in embedded providers
    for (name, star_content) in ALL_PROVIDER_STARS {
        match reg.register_builtin(name, star_content).await {
            Ok(()) => {
                trace!(provider = %name, "Registered ProviderHandle");
            }
            Err(e) => {
                tracing::warn!(
                    provider = %name,
                    error = %e,
                    "Failed to register ProviderHandle — provider.star may have errors"
                );
            }
        }
    }

    // 2. User / project-level overrides (vx provider add)
    for (name, star_content) in load_star_overrides() {
        match reg.register_dynamic(&name, star_content).await {
            Ok(()) => {
                trace!(provider = %name, "Registered user ProviderHandle");
            }
            Err(e) => {
                tracing::warn!(
                    provider = %name,
                    error = %e,
                    "Failed to register user ProviderHandle — provider.star may have errors"
                );
            }
        }
    }
}

pub async fn init_provider_handles() {
    ensure_provider_handles_initialized().await;
}

pub async fn ensure_provider_handles_initialized() {
    PROVIDER_HANDLES_INIT
        .get_or_init(|| async {
            init_provider_handles_inner().await;
        })
        .await;
}

/// Initialize the global constraints registry from embedded provider.star files.
///
/// This parses the optional `constraints = [...]` variable in provider.star.
/// Constraints are applied to the runtime whose name matches the provider,
/// or the first runtime if no name matches.
pub fn init_constraints_registry() {
    let mut rules: HashMap<String, Vec<ConstraintRule>> = HashMap::new();

    for (name, star_content) in ALL_PROVIDER_STARS {
        collect_constraints_from_star(name, star_content, &mut rules);
    }

    for (name, star_content) in load_star_overrides() {
        collect_constraints_from_star(&name, &star_content, &mut rules);
    }

    if let Err(e) = init_constraints_from_star(rules.into_iter().collect()) {
        tracing::warn!("Failed to initialize constraints registry: {}", e);
    }
}

pub fn ensure_constraints_registry_initialized() {
    CONSTRAINTS_INIT.get_or_init(|| {
        init_constraints_registry();
    });
}

pub async fn ensure_provider_metadata_initialized() {
    ensure_provider_handles_initialized().await;
    ensure_constraints_registry_initialized();
}

/// Cached package alias lookup table.
/// Built once on first access, avoids re-parsing all 78 provider.star files on every tool execution.
static PACKAGE_ALIAS_CACHE: OnceLock<HashMap<String, PackageAlias>> = OnceLock::new();

fn build_package_alias_cache() -> HashMap<String, PackageAlias> {
    let mut cache = HashMap::new();

    for (name, star_content) in ALL_PROVIDER_STARS {
        let meta = StarMetadata::parse(star_content);
        if let Some((ecosystem, package)) = &meta.package_alias {
            let alias = PackageAlias {
                ecosystem: ecosystem.clone(),
                package: package.clone(),
                executable: None,
            };

            // Map provider name
            if let Some(ref provider_name) = meta.name {
                cache.insert(provider_name.clone(), alias.clone());
            } else {
                cache.insert(name.to_string(), alias.clone());
            }

            // Map all runtime names and aliases
            for runtime in &meta.runtimes {
                if let Some(ref runtime_name) = runtime.name {
                    cache.insert(runtime_name.clone(), alias.clone());
                }
                for a in &runtime.aliases {
                    cache.insert(a.clone(), alias.clone());
                }
            }
        }
    }

    // Also include user overrides
    for (name, star_content) in load_star_overrides() {
        let meta = StarMetadata::parse(&star_content);
        if let Some((ecosystem, package)) = &meta.package_alias {
            let alias = PackageAlias {
                ecosystem: ecosystem.clone(),
                package: package.clone(),
                executable: None,
            };
            cache.insert(name, alias.clone());
            for runtime in &meta.runtimes {
                if let Some(ref runtime_name) = runtime.name {
                    cache.insert(runtime_name.clone(), alias.clone());
                }
                for a in &runtime.aliases {
                    cache.insert(a.clone(), alias.clone());
                }
            }
        }
    }

    cache
}

pub fn find_package_alias(runtime_name: &str) -> Option<PackageAlias> {
    let cache = PACKAGE_ALIAS_CACHE.get_or_init(build_package_alias_cache);
    cache.get(runtime_name).cloned()
}

/// Cached runtime names list.
static RUNTIME_NAMES_CACHE: OnceLock<Vec<String>> = OnceLock::new();

pub fn available_runtime_names() -> Vec<String> {
    RUNTIME_NAMES_CACHE
        .get_or_init(|| {
            let mut names = Vec::new();

            for (name, star_content) in ALL_PROVIDER_STARS {
                names.extend(extract_runtime_lookup_names(name, star_content));
            }

            for (name, star_content) in load_star_overrides() {
                names.extend(extract_runtime_lookup_names(&name, &star_content));
            }

            names.sort();
            names.dedup();
            names
        })
        .clone()
}

fn collect_constraints_from_star(
    provider_name: &str,
    content: &str,
    out: &mut HashMap<String, Vec<ConstraintRule>>,
) {
    // Fast pre-filter: skip providers that don't mention "constraints" at all.
    // This avoids creating a Starlark engine + full AST evaluation for the ~90%
    // of providers that have no constraints, saving significant startup time.
    if !content.contains("constraints") {
        return;
    }

    let engine = StarlarkEngine::new();
    let script_path = Path::new(provider_name);

    let Ok(Some(value)) = engine.get_variable(script_path, content, "constraints") else {
        return;
    };

    let meta = StarMetadata::parse(content);
    let runtime_names: Vec<String> = meta
        .runtimes
        .iter()
        .filter_map(|r| r.name.clone())
        .collect();

    let default_runtime = if runtime_names.iter().any(|n| n == provider_name) {
        Some(provider_name.to_string())
    } else {
        runtime_names.first().cloned()
    };

    let Some(default_runtime) = default_runtime else {
        return;
    };

    for (runtime, rules) in parse_constraints_value(&value, &default_runtime) {
        out.entry(runtime).or_default().extend(rules);
    }
}

fn parse_constraints_value(
    value: &serde_json::Value,
    default_runtime: &str,
) -> Vec<(String, Vec<ConstraintRule>)> {
    let Some(entries) = value.as_array() else {
        return Vec::new();
    };

    let mut rules_by_runtime: HashMap<String, Vec<ConstraintRule>> = HashMap::new();

    for entry in entries {
        let Some(obj) = entry.as_object() else {
            continue;
        };

        let when = obj.get("when").and_then(|v| v.as_str()).unwrap_or("*");

        let runtime_name = obj
            .get("runtime")
            .and_then(|v| v.as_str())
            .unwrap_or(default_runtime)
            .to_string();

        let mut constraints: Vec<DependencyConstraint> = Vec::new();

        if let Some(reqs) = obj.get("requires").and_then(|v| v.as_array()) {
            for req in reqs {
                if let Some(dep) = parse_constraint_dep(req, false) {
                    constraints.push(dep);
                }
            }
        }

        if let Some(reqs) = obj.get("recommends").and_then(|v| v.as_array()) {
            for req in reqs {
                if let Some(dep) = parse_constraint_dep(req, true) {
                    constraints.push(dep);
                }
            }
        }

        if constraints.is_empty() {
            continue;
        }

        let mut rule = ConstraintRule::with_manifest_pattern(ManifestVersionPattern::new(when));
        for constraint in constraints {
            rule = rule.with_constraint(constraint);
        }

        rules_by_runtime.entry(runtime_name).or_default().push(rule);
    }

    rules_by_runtime.into_iter().collect()
}

fn parse_constraint_dep(
    value: &serde_json::Value,
    force_optional: bool,
) -> Option<DependencyConstraint> {
    let obj = value.as_object()?;
    let runtime = obj.get("runtime")?.as_str()?.to_string();
    let version = obj.get("version").and_then(|v| v.as_str()).unwrap_or("*");

    let (min, max) = parse_version_min_max(version);
    let mut constraint = DependencyConstraint::required(runtime);

    if let Some(min) = min {
        constraint = constraint.min(min);
    }
    if let Some(max) = max {
        constraint = constraint.max(max);
    }

    if let Some(rec) = obj.get("recommended").and_then(|v| v.as_str()) {
        constraint = constraint.recommended(rec);
    }

    if let Some(reason) = obj.get("reason").and_then(|v| v.as_str()) {
        constraint = constraint.reason(reason);
    }

    let optional = obj
        .get("optional")
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
        || force_optional;

    if optional {
        constraint.optional = true;
    }

    Some(constraint)
}

fn parse_version_min_max(version_req: &str) -> (Option<String>, Option<String>) {
    let req = VersionRequest::parse(version_req);
    match &req.constraint {
        VersionConstraint::Range(constraints) => {
            let mut min = None;
            let mut max = None;
            for c in constraints {
                match c.op {
                    RangeOp::Gte | RangeOp::Gt => {
                        min = Some(c.version.to_string());
                    }
                    RangeOp::Lte | RangeOp::Lt => {
                        max = Some(c.version.to_string());
                    }
                    _ => {}
                }
            }
            (min, max)
        }
        VersionConstraint::Caret(v) => {
            let min = v.to_string();
            let max = if v.major > 0 {
                format!("{}.0.0", v.major + 1)
            } else if v.minor > 0 {
                format!("0.{}.0", v.minor + 1)
            } else {
                format!("0.0.{}", v.patch + 1)
            };
            (Some(min), Some(max))
        }
        VersionConstraint::Tilde(v) => {
            let min = v.to_string();
            let max = format!("{}.{}.0", v.major, v.minor + 1);
            (Some(min), Some(max))
        }
        VersionConstraint::Exact(v) => {
            let ver = v.to_string();
            (Some(ver.clone()), Some(ver))
        }
        _ => (None, None),
    }
}

/// Build a RuntimeMap from the global ProviderHandle registry (RFC-0037)
///
/// This replaces the old `RuntimeMap::from_manifests()` approach.
/// The RuntimeMap is built from `provider.star` metadata loaded into
/// `GLOBAL_REGISTRY` at startup via `init_provider_handles()`.
///
/// Falls back to an empty RuntimeMap if the registry is not yet initialized.
pub fn build_runtime_map() -> vx_resolver::RuntimeMap {
    use vx_resolver::{RuntimeDependency, RuntimeMap, RuntimeSpec};

    let Ok(registry) = vx_starlark::handle::GLOBAL_REGISTRY.try_read() else {
        return RuntimeMap::empty();
    };

    let mut map = RuntimeMap::empty();

    for (_name, handle) in registry.iter() {
        for runtime_meta in handle.runtime_metas() {
            let mut spec = RuntimeSpec::new(&runtime_meta.name, &runtime_meta.description);
            spec.executable = Some(runtime_meta.executable.clone());
            spec.aliases = runtime_meta.aliases.clone();
            spec.priority = runtime_meta.priority as i32;
            spec.command_prefix = runtime_meta.command_prefix.clone();

            // Handle bundled_with: add a provided_by dependency so the resolver
            // looks in the parent runtime's store directory for this executable.
            // e.g., uvx is bundled_with uv → look in ~/.vx/store/uv/ for uvx
            if let Some(ref bundled_with) = runtime_meta.bundled_with {
                let dep = RuntimeDependency::required(
                    bundled_with.clone(),
                    format!("{} is bundled with {}", runtime_meta.name, bundled_with),
                )
                .provided_by(bundled_with.clone());
                spec.dependencies.push(dep);
            }

            // Register system_paths glob patterns for detection
            // (e.g., MSVC cl.exe paths that are not on system PATH)
            if !runtime_meta.system_paths.is_empty() {
                map.register_system_paths(
                    runtime_meta.name.clone(),
                    runtime_meta.system_paths.clone(),
                );
            }

            map.register(spec);
        }
    }

    map
}

/// Get platform label for a runtime from the ProviderHandle registry.
///
/// Returns the platform label (e.g., "Windows", "macOS") if the runtime
/// has platform constraints, or None if it supports all platforms.
/// This is a best-effort synchronous lookup; for full accuracy use the async API.
pub fn get_runtime_platform_label(runtime_name: &str) -> Option<String> {
    // Try to get from ProviderHandle registry (provider.star)
    // This is a sync wrapper — for now we check ALL_PROVIDER_STARS metadata
    // A full implementation would query ProviderMeta.platforms from the handle
    let _ = runtime_name;
    None
}

/// Create a runtime context for operations
pub fn create_context() -> anyhow::Result<RuntimeContext> {
    create_runtime_context()
}

/// Extension trait for ProviderRegistry to provide convenience methods
pub trait ProviderRegistryExt {
    /// Get a runtime by name
    fn get_runtime(&self, name: &str) -> Option<Arc<dyn Runtime>>;

    /// Check if a runtime is supported
    fn supports_runtime(&self, name: &str) -> bool;

    /// List all runtime names
    fn list_runtimes(&self) -> Vec<String>;

    /// Get all providers
    fn get_providers(&self) -> Vec<Arc<dyn Provider>>;
}

impl ProviderRegistryExt for ProviderRegistry {
    fn get_runtime(&self, name: &str) -> Option<Arc<dyn Runtime>> {
        ProviderRegistry::get_runtime(self, name)
    }

    fn supports_runtime(&self, name: &str) -> bool {
        self.supports(name)
    }

    fn list_runtimes(&self) -> Vec<String> {
        self.runtime_names()
    }

    fn get_providers(&self) -> Vec<Arc<dyn Provider>> {
        self.providers()
    }
}

// =============================================================================
// Build Diagnostics Storage (RFC 0029 Phase 2)
// =============================================================================

/// Stored build diagnostics from `create_registry()`
///
/// Accessible via `get_build_diagnostics()` for `vx info --warnings`.
#[derive(Debug, Clone, Default)]
pub struct BuildDiagnostics {
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
}

static BUILD_DIAGNOSTICS: OnceLock<BuildDiagnostics> = OnceLock::new();

/// Get build diagnostics from the last `create_registry()` call
pub fn get_build_diagnostics() -> &'static BuildDiagnostics {
    static EMPTY: OnceLock<BuildDiagnostics> = OnceLock::new();
    BUILD_DIAGNOSTICS
        .get()
        .unwrap_or_else(|| EMPTY.get_or_init(BuildDiagnostics::default))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_embedded_stars_exist() {
        assert!(
            !ALL_PROVIDER_STARS.is_empty(),
            "Expected embedded provider.star files, found none"
        );
    }

    #[test]
    fn test_create_registry_has_providers() {
        let registry = create_registry();
        assert!(
            !registry.runtime_names().is_empty(),
            "Registry should have providers"
        );
    }
}
