[package]
name = "vx-tool-uv"
version.workspace = true
edition.workspace = true
description = "UV tool support for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-core = { version = "0.4.0", path = "../../vx-core" }
vx-installer = { version = "0.4.0", path = "../../vx-installer", features = [
    "progress",
] }
vx-paths = { version = "0.3.1", path = "../../vx-paths" }
vx-plugin = { version = "0.4.0", path = "../../vx-plugin" }
vx-version = { version = "0.2.2", path = "../../vx-version" }
vx-tool-standard = { version = "0.4.0", path = "../../vx-tool-standard" }
vx-config = { version = "0.4.1", path = "../../vx-config" }
anyhow = { workspace = true }
which = "8.0"
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
