[package]
name = "vx-tool-uv"
version.workspace = true
edition.workspace = true
description = "UV tool support for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-core = { version = "0.2.5", path = "../../vx-core" }
anyhow = { workspace = true }
which = "8.0"
async-trait = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
