// This crate is managed by `cargo-hakari`.
// It unifies feature sets across the workspace to reduce duplicate dependency compilations.
// Do not edit this file manually. Run `cargo hakari generate` to update.
