"""Unit tests for the lockfile drift checker."""

from __future__ import annotations

import sys
import unittest
import unittest.mock
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import check_lockfile_drift as drift  # noqa: E402


def lockfile(*packages: tuple[str, str, tuple[str, ...]]) -> str:
    """Build a minimal lockfile v4 body from `(name, version, deps)` tuples.

    A dependency is written bare when it is unambiguous and as
    `"name version"` when several versions exist, matching what cargo emits.
    """

    versions: dict[str, list[str]] = {}
    for name, version, _deps in packages:
        versions.setdefault(name, []).append(version)

    blocks = ["# This file is automatically @generated by Cargo.", "version = 4", ""]
    for name, version, deps in packages:
        blocks.append("[[package]]")
        blocks.append(f'name = "{name}"')
        blocks.append(f'version = "{version}"')
        if deps:
            blocks.append("dependencies = [")
            for dep in deps:
                dep_name = dep.split(" ")[0]
                rendered = dep if len(versions.get(dep_name, [])) > 1 else dep_name
                blocks.append(f' "{rendered}",')
            blocks.append("]")
        blocks.append("")
    return "\n".join(blocks)


class ParseVersionTests(unittest.TestCase):
    def test_orders_release_versions(self) -> None:
        self.assertLess(drift.parse_version("0.52.0"), drift.parse_version("0.61.2"))
        self.assertLess(drift.parse_version("1.9.0"), drift.parse_version("1.10.0"))
        self.assertLess(drift.parse_version("0.3.4"), drift.parse_version("0.4.3"))

    def test_compares_numeric_parts_not_text(self) -> None:
        self.assertLess(drift.parse_version("0.9.0"), drift.parse_version("0.10.0"))

    def test_ignores_pre_release_and_build_metadata(self) -> None:
        self.assertEqual(drift.parse_version("1.2.3"), drift.parse_version("1.2.3+build.5"))
        self.assertEqual(drift.parse_version("1.2.3"), drift.parse_version("1.2.3-rc.1"))

    def test_tolerates_a_partial_version(self) -> None:
        self.assertEqual(drift.parse_version("1"), (1,))
        self.assertEqual(drift.parse_version(""), (0,))


class ParseLockfileTests(unittest.TestCase):
    def test_resolves_a_bare_dependency_name(self) -> None:
        text = lockfile(
            ("colored", "3.1.1", ("windows-sys",)),
            ("windows-sys", "0.61.2", ()),
        )

        parsed = drift.parse_lockfile(text)

        self.assertEqual(parsed["colored 3.1.1"], {"windows-sys": "0.61.2"})

    def test_keeps_the_qualified_form_when_several_versions_exist(self) -> None:
        text = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        parsed = drift.parse_lockfile(text)

        self.assertEqual(parsed["colored 3.1.1"], {"windows-sys": "0.61.2"})
        self.assertEqual(parsed["rustyline 14.0.0"], {"windows-sys": "0.52.0"})

    def test_a_package_without_dependencies_has_no_edges(self) -> None:
        self.assertEqual(drift.parse_lockfile(lockfile(("adler2", "2.0.1", ()))), {"adler2 2.0.1": {}})


class FindDriftTests(unittest.TestCase):
    def base_and_head(self, head_windows: str) -> tuple[dict, dict]:
        base = drift.parse_lockfile(
            lockfile(
                ("colored", "3.1.1", ("windows-sys 0.61.2",)),
                ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
                ("windows-sys", "0.52.0", ()),
                ("windows-sys", "0.61.2", ()),
            )
        )
        head = drift.parse_lockfile(
            lockfile(
                ("colored", "3.1.1", (f"windows-sys {head_windows}",)),
                ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
                ("windows-sys", "0.52.0", ()),
                ("windows-sys", "0.61.2", ()),
            )
        )
        return base, head

    def test_a_re_pointed_edge_to_an_older_version_is_drift(self) -> None:
        base, head = self.base_and_head("0.52.0")

        found = drift.find_drift(base, head)

        self.assertEqual(len(found), 1)
        self.assertEqual(found[0].dependency, "windows-sys")
        self.assertEqual(found[0].base_version, "0.61.2")
        self.assertEqual(found[0].head_version, "0.52.0")
        self.assertIn("windows-sys 0.61.2 -> 0.52.0", found[0].describe())

    def test_an_unchanged_edge_is_not_drift(self) -> None:
        base, head = self.base_and_head("0.61.2")

        self.assertEqual(drift.find_drift(base, head), [])

    def test_an_upgrade_is_not_drift(self) -> None:
        base = drift.parse_lockfile(
            lockfile(("tempfile", "3.27.0", ("getrandom 0.3.4",)), ("getrandom", "0.3.4", ()), ("getrandom", "0.4.3", ()))
        )
        head = drift.parse_lockfile(
            lockfile(("tempfile", "3.27.0", ("getrandom 0.4.3",)), ("getrandom", "0.3.4", ()), ("getrandom", "0.4.3", ()))
        )

        self.assertEqual(drift.find_drift(base, head), [])

    def test_a_package_missing_on_one_side_is_skipped(self) -> None:
        base = drift.parse_lockfile(lockfile(("gone", "1.0.0", ("dep 1.0.0",)), ("dep", "1.0.0", ())))
        head = drift.parse_lockfile(lockfile(("dep", "1.0.0", ())))

        self.assertEqual(drift.find_drift(base, head), [])

    def test_every_drift_is_reported_not_just_the_first(self) -> None:
        base = drift.parse_lockfile(
            lockfile(
                ("a", "1.0.0", ("shared 3.0.0",)),
                ("b", "1.0.0", ("shared 3.0.0",)),
                ("shared", "2.0.0", ()),
                ("shared", "3.0.0", ()),
            )
        )
        head = drift.parse_lockfile(
            lockfile(
                ("a", "1.0.0", ("shared 2.0.0",)),
                ("b", "1.0.0", ("shared 2.0.0",)),
                ("shared", "2.0.0", ()),
                ("shared", "3.0.0", ()),
            )
        )

        found = drift.find_drift(base, head)

        self.assertEqual([item.package for item in found], ["a", "b"])


class MainTests(unittest.TestCase):
    def test_a_drifted_head_exits_with_the_policy_code(self) -> None:
        base = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )
        head = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        with unittest.mock.patch.object(drift, "read_lockfile", side_effect=[base, head]):
            with unittest.mock.patch.object(drift, "merge_tree", return_value=None):
                self.assertEqual(drift.main(["--base", "main", "--head", "pr"]), 1)

    def test_an_unreadable_ref_exits_with_the_infrastructure_code(self) -> None:
        self.assertEqual(drift.main(["--base", "main", "--head", "definitely-not-a-ref"]), 2)

    def test_json_output_reports_the_drift(self) -> None:
        base = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )
        head = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        with unittest.mock.patch.object(drift, "read_lockfile", side_effect=[base, head]):
            with unittest.mock.patch.object(drift, "merge_tree", return_value=None):
                code = drift.main(["--base", "main", "--head", "pr", "--format", "json"])

        self.assertEqual(code, 1)


if __name__ == "__main__":
    unittest.main()
