"""Unit tests for the lockfile drift checker."""

from __future__ import annotations

import sys
import unittest
import unittest.mock
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import check_lockfile_drift as drift  # noqa: E402


def lockfile(*packages: tuple[str, str, tuple[str, ...]]) -> str:
    """Build a minimal lockfile v4 body from `(name, version, deps)` tuples.

    A dependency is written bare when it is unambiguous and as
    `"name version"` when several versions exist, matching what cargo emits.
    """

    versions: dict[str, list[str]] = {}
    for name, version, _deps in packages:
        versions.setdefault(name, []).append(version)

    blocks = ["# This file is automatically @generated by Cargo.", "version = 4", ""]
    for name, version, deps in packages:
        blocks.append("[[package]]")
        blocks.append(f'name = "{name}"')
        blocks.append(f'version = "{version}"')
        if deps:
            blocks.append("dependencies = [")
            for dep in deps:
                dep_name = dep.split(" ")[0]
                rendered = dep if len(versions.get(dep_name, [])) > 1 else dep_name
                blocks.append(f' "{rendered}",')
            blocks.append("]")
        blocks.append("")
    return "\n".join(blocks)


class ParseVersionTests(unittest.TestCase):
    def test_orders_release_versions(self) -> None:
        self.assertLess(drift.parse_version("0.52.0"), drift.parse_version("0.61.2"))
        self.assertLess(drift.parse_version("1.9.0"), drift.parse_version("1.10.0"))
        self.assertLess(drift.parse_version("0.3.4"), drift.parse_version("0.4.3"))

    def test_compares_numeric_parts_not_text(self) -> None:
        self.assertLess(drift.parse_version("0.9.0"), drift.parse_version("0.10.0"))

    def test_ignores_pre_release_and_build_metadata(self) -> None:
        self.assertEqual(drift.parse_version("1.2.3"), drift.parse_version("1.2.3+build.5"))
        self.assertEqual(drift.parse_version("1.2.3"), drift.parse_version("1.2.3-rc.1"))

    def test_tolerates_a_partial_version(self) -> None:
        self.assertEqual(drift.parse_version("1"), (1,))
        self.assertEqual(drift.parse_version(""), (0,))


class ParseLockfileTests(unittest.TestCase):
    def test_resolves_a_bare_dependency_name(self) -> None:
        text = lockfile(
            ("colored", "3.1.1", ("windows-sys",)),
            ("windows-sys", "0.61.2", ()),
        )

        parsed = drift.parse_lockfile(text)

        self.assertEqual(parsed["colored 3.1.1"], {"windows-sys": "0.61.2"})

    def test_keeps_the_qualified_form_when_several_versions_exist(self) -> None:
        text = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        parsed = drift.parse_lockfile(text)

        self.assertEqual(parsed["colored 3.1.1"], {"windows-sys": "0.61.2"})
        self.assertEqual(parsed["rustyline 14.0.0"], {"windows-sys": "0.52.0"})

    def test_a_package_without_dependencies_has_no_edges(self) -> None:
        self.assertEqual(drift.parse_lockfile(lockfile(("adler2", "2.0.1", ()))), {"adler2 2.0.1": {}})

    # A checker that silently fails to parse dependency edges reports "no
    # findings" rather than an error, which is worse than not running. CRLF
    # line endings have caused exactly that, so both endings are pinned.
    def test_crlf_line_endings_parse_identically(self) -> None:
        text = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        expected = drift.parse_lockfile(text)

        self.assertEqual(expected["colored 3.1.1"], {"windows-sys": "0.61.2"})
        self.assertEqual(drift.parse_lockfile(text.replace("\n", "\r\n")), expected)
        self.assertEqual(drift.parse_lockfile(text.replace("\n", "\r")), expected)

    def test_drift_is_detected_whatever_the_line_endings(self) -> None:
        base = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )
        head = base.replace(' "windows-sys 0.61.2",', ' "windows-sys 0.52.0",')

        for ending in ("\n", "\r\n"):
            with self.subTest(ending=repr(ending)):
                found = drift.find_drift(
                    drift.parse_lockfile(base.replace("\n", ending)),
                    drift.parse_lockfile(head.replace("\n", ending)),
                )
                self.assertEqual(
                    [item.describe() for item in found],
                    ["colored 3.1.1: windows-sys 0.61.2 -> 0.52.0"],
                )


class FindDriftTests(unittest.TestCase):
    def base_and_head(self, head_windows: str) -> tuple[dict, dict]:
        base = drift.parse_lockfile(
            lockfile(
                ("colored", "3.1.1", ("windows-sys 0.61.2",)),
                ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
                ("windows-sys", "0.52.0", ()),
                ("windows-sys", "0.61.2", ()),
            )
        )
        head = drift.parse_lockfile(
            lockfile(
                ("colored", "3.1.1", (f"windows-sys {head_windows}",)),
                ("rustyline", "14.0.0", ("windows-sys 0.52.0",)),
                ("windows-sys", "0.52.0", ()),
                ("windows-sys", "0.61.2", ()),
            )
        )
        return base, head

    def test_a_re_pointed_edge_to_an_older_version_is_drift(self) -> None:
        base, head = self.base_and_head("0.52.0")

        found = drift.find_drift(base, head)

        self.assertEqual(len(found), 1)
        self.assertEqual(found[0].dependency, "windows-sys")
        self.assertEqual(found[0].base_version, "0.61.2")
        self.assertEqual(found[0].head_version, "0.52.0")
        self.assertIn("windows-sys 0.61.2 -> 0.52.0", found[0].describe())

    def test_an_unchanged_edge_is_not_drift(self) -> None:
        base, head = self.base_and_head("0.61.2")

        self.assertEqual(drift.find_drift(base, head), [])

    def test_an_upgrade_is_not_drift(self) -> None:
        base = drift.parse_lockfile(
            lockfile(("tempfile", "3.27.0", ("getrandom 0.3.4",)), ("getrandom", "0.3.4", ()), ("getrandom", "0.4.3", ()))
        )
        head = drift.parse_lockfile(
            lockfile(("tempfile", "3.27.0", ("getrandom 0.4.3",)), ("getrandom", "0.3.4", ()), ("getrandom", "0.4.3", ()))
        )

        self.assertEqual(drift.find_drift(base, head), [])

    def test_a_package_missing_on_one_side_is_skipped(self) -> None:
        base = drift.parse_lockfile(lockfile(("gone", "1.0.0", ("dep 1.0.0",)), ("dep", "1.0.0", ())))
        head = drift.parse_lockfile(lockfile(("dep", "1.0.0", ())))

        self.assertEqual(drift.find_drift(base, head), [])

    def test_every_drift_is_reported_not_just_the_first(self) -> None:
        base = drift.parse_lockfile(
            lockfile(
                ("a", "1.0.0", ("shared 3.0.0",)),
                ("b", "1.0.0", ("shared 3.0.0",)),
                ("shared", "2.0.0", ()),
                ("shared", "3.0.0", ()),
            )
        )
        head = drift.parse_lockfile(
            lockfile(
                ("a", "1.0.0", ("shared 2.0.0",)),
                ("b", "1.0.0", ("shared 2.0.0",)),
                ("shared", "2.0.0", ()),
                ("shared", "3.0.0", ()),
            )
        )

        found = drift.find_drift(base, head)

        self.assertEqual([item.package for item in found], ["a", "b"])


class BumpClaimTests(unittest.TestCase):
    def test_reads_a_plain_crate_bump(self) -> None:
        claims = drift.parse_bump_claims("fix(deps): update rust crate tower-http to 0.7")

        self.assertEqual([(c.crate, c.version) for c in claims], [("tower-http", "0.7")])

    def test_reads_a_version_prefixed_with_v(self) -> None:
        claims = drift.parse_bump_claims("chore(deps): update rust crate uuid to v1.26.1")

        self.assertEqual([(c.crate, c.version) for c in claims], [("uuid", "1.26.1")])

    def test_reads_a_monorepo_bump(self) -> None:
        claims = drift.parse_bump_claims("chore(deps): update serde monorepo to v1.0.229")

        self.assertEqual([(c.crate, c.version) for c in claims], [("serde", "1.0.229")])

    # A pull request that claims no bump must not be held to one, so that a
    # change touching no dependencies stays out of the report.
    def test_a_title_without_a_bump_claim_produces_nothing(self) -> None:
        for title in (
            "fix(windows): preserve nested PATH resolution",
            "chore(deps): update actions/setup-node action to v7",
            "",
        ):
            with self.subTest(title=title):
                self.assertEqual(drift.parse_bump_claims(title), [])

    def test_a_claim_is_satisfied_by_a_longer_resolved_version(self) -> None:
        self.assertTrue(drift.version_matches("0.7.1", "0.7"))
        self.assertTrue(drift.version_matches("1.0.229", "1.0.229"))
        self.assertFalse(drift.version_matches("0.6.11", "0.7"))

    def test_a_monorepo_claim_covers_the_crates_it_publishes(self) -> None:
        self.assertTrue(drift.crate_matches("serde_derive", "serde"))
        self.assertTrue(drift.crate_matches("zstd-sys", "zstd"))
        self.assertFalse(drift.crate_matches("tower", "tower-http"))


class MissedBumpTests(unittest.TestCase):
    def lock(self, *packages: tuple[str, str]) -> list[tuple[str, str]]:
        return list(packages)

    def test_a_delivered_bump_is_not_reported(self) -> None:
        claims = drift.parse_bump_claims("fix(deps): update rust crate tower-http to 0.7")

        found = drift.find_unfulfilled_bumps(
            claims, self.lock(("tower-http", "0.7.1"), ("tokio", "1.53.1"))
        )

        self.assertEqual(found, [])

    # The failure mode: a later commit re-resolved the lockfile and dropped the
    # package the branch was opened to bump.
    def test_a_bump_the_lockfile_does_not_contain_is_reported(self) -> None:
        claims = drift.parse_bump_claims("fix(deps): update rust crate tower-http to 0.7")

        found = drift.find_unfulfilled_bumps(
            claims, self.lock(("tower-http", "0.6.11"))
        )

        self.assertEqual(len(found), 1)
        self.assertEqual(found[0].crate, "tower-http")
        self.assertEqual(found[0].claimed_version, "0.7")
        self.assertEqual(found[0].found_versions, ["0.6.11"])
        self.assertIn("not delivered", found[0].describe())

    def test_a_crate_missing_from_the_lockfile_is_reported(self) -> None:
        claims = drift.parse_bump_claims("fix(deps): update rust crate tower-http to 0.7")

        found = drift.find_unfulfilled_bumps(claims, self.lock(("tokio", "1.53.1")))

        self.assertEqual(len(found), 1)
        self.assertEqual(found[0].found_versions, [])
        self.assertIn("not in the lockfile", found[0].describe())

    def test_a_monorepo_bump_is_satisfied_by_any_published_crate(self) -> None:
        claims = drift.parse_bump_claims("chore(deps): update serde monorepo to v1.0.229")

        found = drift.find_unfulfilled_bumps(
            claims, self.lock(("serde", "1.0.228"), ("serde_derive", "1.0.229"))
        )

        self.assertEqual(found, [])

    def test_no_claims_means_no_findings(self) -> None:
        found = drift.find_unfulfilled_bumps([], self.lock(("tower-http", "0.6.11")))

        self.assertEqual(found, [])


class MainTests(unittest.TestCase):
    def test_a_drifted_head_exits_with_the_policy_code(self) -> None:
        base = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )
        head = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        with unittest.mock.patch.object(drift, "read_lockfile", side_effect=[base, head]):
            with unittest.mock.patch.object(drift, "merge_tree", return_value=None):
                self.assertEqual(drift.main(["--base", "main", "--head", "pr"]), 1)

    def test_an_unreadable_ref_exits_with_the_infrastructure_code(self) -> None:
        self.assertEqual(drift.main(["--base", "main", "--head", "definitely-not-a-ref"]), 2)

    # A missed bump warns by default: failing a merge over a title this parser
    # misread is worse than merging a pull request that did nothing.
    def test_a_missed_bump_warns_without_failing_by_default(self) -> None:
        base = lockfile(
            ("tower-http", "0.6.11", ()),
            ("tokio", "1.52.3", ("tower-http",)),
        )
        head = base

        with unittest.mock.patch.object(drift, "read_lockfile", side_effect=[base, head]):
            with unittest.mock.patch.object(drift, "merge_tree", return_value=None):
                code = drift.main(
                    [
                        "--base",
                        "main",
                        "--head",
                        "pr",
                        "--title",
                        "fix(deps): update rust crate tower-http to 0.7",
                    ]
                )

        self.assertEqual(code, 0)

    def test_strict_turns_a_missed_bump_into_a_failure(self) -> None:
        base = lockfile(
            ("tower-http", "0.6.11", ()),
            ("tokio", "1.52.3", ("tower-http",)),
        )
        head = base

        with unittest.mock.patch.object(drift, "read_lockfile", side_effect=[base, head]):
            with unittest.mock.patch.object(drift, "merge_tree", return_value=None):
                code = drift.main(
                    [
                        "--base",
                        "main",
                        "--head",
                        "pr",
                        "--title",
                        "fix(deps): update rust crate tower-http to 0.7",
                        "--strict",
                    ]
                )

        self.assertEqual(code, 1)

    def test_json_output_reports_the_drift(self) -> None:
        base = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.61.2",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )
        head = lockfile(
            ("colored", "3.1.1", ("windows-sys 0.52.0",)),
            ("windows-sys", "0.52.0", ()),
            ("windows-sys", "0.61.2", ()),
        )

        with unittest.mock.patch.object(drift, "read_lockfile", side_effect=[base, head]):
            with unittest.mock.patch.object(drift, "merge_tree", return_value=None):
                code = drift.main(["--base", "main", "--head", "pr", "--format", "json"])

        self.assertEqual(code, 1)


if __name__ == "__main__":
    unittest.main()
