//! Script generators for each [`ShimType`]
//!
//! Split out of `shim.rs` to keep that module focused on the shim model and
//! filesystem operations.

use super::{ShimType, VX_SHIM_MARKER};
use crate::shim::Shim;

/// Comment token used by a shim type for its marker line
fn comment_token(shim_type: ShimType) -> &'static str {
    match shim_type {
        ShimType::Batch => "REM",
        ShimType::PowerShell | ShimType::Shell => "#",
    }
}

/// Marker line identifying a vx-generated shim for the given type
pub(crate) fn marker_line(shim_type: ShimType) -> String {
    format!(
        "{} Generated by {}. Do not edit; managed by 'vx shim'.",
        comment_token(shim_type),
        VX_SHIM_MARKER
    )
}

/// Generate Windows batch script content
pub(crate) fn batch(shim: &Shim) -> String {
    let mut lines = vec![
        "@echo off".to_string(),
        "setlocal".to_string(),
        marker_line(ShimType::Batch),
    ];

    // Add environment variables
    for (key, value) in &shim.env {
        lines.push(format!("set {}={}", key, value));
    }

    // Add working directory change if specified
    if let Some(ref dir) = shim.working_dir {
        lines.push(format!("cd /d \"{}\"", dir.display()));
    }

    // Build the command
    let target_str = shim.target.display().to_string();
    let args_str = if shim.args.is_empty() {
        " ".to_string()
    } else {
        format!(" {} ", shim.args.join(" "))
    };

    lines.push(format!("\"{}\"{}%*", target_str, args_str));

    // Propagate the exit code of the wrapped command to our caller
    lines.push("exit /b %ERRORLEVEL%".to_string());

    lines.join("\r\n")
}

/// Generate PowerShell script content
pub(crate) fn powershell(shim: &Shim) -> String {
    let mut lines = vec![
        "#!/usr/bin/env pwsh".to_string(),
        marker_line(ShimType::PowerShell),
    ];

    // Add environment variables
    for (key, value) in &shim.env {
        lines.push(format!("$env:{} = '{}'", key, value));
    }

    // Add working directory change if specified
    if let Some(ref dir) = shim.working_dir {
        lines.push(format!("Set-Location -Path \"{}\"", dir.display()));
    }

    // Build the command
    let mut cmd_parts = vec![format!("\"{}\"", shim.target.display())];
    cmd_parts.extend(shim.args.iter().cloned());
    cmd_parts.push("$args".to_string());

    lines.push(format!("& {}", cmd_parts.join(" ")));

    // Propagate the exit code of the wrapped command to our caller
    lines.push("exit $LASTEXITCODE".to_string());

    lines.join("\n")
}

/// Generate Unix shell script content
///
/// Target paths are emitted with forward slashes so the same script also works
/// from Git Bash / MSYS2 on Windows, where `Path::display()` would otherwise
/// produce backslashes that a POSIX shell treats as escapes.
pub(crate) fn shell(shim: &Shim) -> String {
    let mut lines = vec!["#!/bin/sh".to_string(), marker_line(ShimType::Shell)];

    // Add environment variables
    for (key, value) in &shim.env {
        lines.push(format!("{}='{}'", key, value));
        lines.push(format!("export {}", key));
    }

    // Add working directory change if specified
    if let Some(ref dir) = shim.working_dir {
        lines.push(format!("cd \"{}\"", dir.display()));
    }

    // Build the command
    let mut cmd_parts = vec![format!(
        "\"{}\"",
        shim.target.display().to_string().replace('\\', "/")
    )];
    cmd_parts.extend(shim.args.iter().cloned());
    cmd_parts.push("\"$@\"".to_string());

    // `exec` replaces this process, so the exit code needs no handling
    lines.push(format!("exec {}", cmd_parts.join(" ")));

    lines.join("\n")
}
