//! Script generators for each [`ShimType`]
//!
//! Split out of `shim.rs` to keep that module focused on the shim model and
//! filesystem operations.

use super::{ShimType, VX_SHIM_MARKER};
use crate::shim::Shim;

/// Arguments with only these characters are literal in every supported shell.
fn is_plain_argument(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"-_.:/@=+".contains(&byte))
}

fn shell_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn shell_argument(value: &str) -> String {
    if is_plain_argument(value) {
        value.to_string()
    } else {
        shell_literal(value)
    }
}

fn shell_path(value: &str) -> String {
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('$', "\\$")
            .replace('`', "\\`")
    )
}

fn powershell_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// Quote one batch argument, including CRT backslash/quote rules and the
/// percent expansion performed while cmd.exe reads a batch file.
fn batch_literal(value: &str) -> String {
    let mut quoted = String::from("\"");
    let mut backslashes = 0;
    for character in value.chars() {
        if character == '\\' {
            backslashes += 1;
            continue;
        }
        quoted.push_str(&"\\".repeat(if character == '"' {
            backslashes * 2
        } else {
            backslashes
        }));
        backslashes = 0;
        match character {
            '"' => quoted.push_str("\"\""),
            '%' => quoted.push_str("%%"),
            _ => quoted.push(character),
        }
    }
    quoted.push_str(&"\\".repeat(backslashes * 2));
    quoted.push('"');
    quoted
}

fn batch_argument(value: &str) -> String {
    if is_plain_argument(value) {
        value.to_string()
    } else {
        batch_literal(value)
    }
}

/// Comment token used by a shim type for its marker line
fn comment_token(shim_type: ShimType) -> &'static str {
    match shim_type {
        ShimType::Batch => "REM",
        ShimType::PowerShell | ShimType::Shell => "#",
    }
}

/// Marker line identifying a vx-generated shim for the given type
pub(crate) fn marker_line(shim_type: ShimType) -> String {
    format!(
        "{} Generated by {}. Do not edit; managed by 'vx shim'.",
        comment_token(shim_type),
        VX_SHIM_MARKER
    )
}

/// Generate Windows batch script content
pub(crate) fn batch(shim: &Shim) -> String {
    let mut lines = vec![
        "@echo off".to_string(),
        "setlocal DisableDelayedExpansion".to_string(),
        marker_line(ShimType::Batch),
    ];

    // Add environment variables
    for (key, value) in &shim.env {
        lines.push(format!("set \"{}={}\"", key, value.replace('%', "%%")));
    }

    // Add working directory change if specified
    if let Some(ref dir) = shim.working_dir {
        lines.push(format!(
            "cd /d {}",
            batch_literal(&dir.display().to_string())
        ));
    }

    // Build the command
    let target_str = shim.target.display().to_string();
    let args_str = if shim.args.is_empty() {
        " ".to_string()
    } else {
        format!(
            " {} ",
            shim.args
                .iter()
                .map(|arg| batch_argument(arg))
                .collect::<Vec<_>>()
                .join(" ")
        )
    };

    lines.push(format!("{}{}%*", batch_literal(&target_str), args_str));

    // Propagate the exit code of the wrapped command to our caller
    lines.push("exit /b %ERRORLEVEL%".to_string());

    lines.join("\r\n")
}

/// Generate PowerShell script content
pub(crate) fn powershell(shim: &Shim) -> String {
    let mut lines = vec![
        "#!/usr/bin/env pwsh".to_string(),
        marker_line(ShimType::PowerShell),
    ];

    // Add environment variables
    for (key, value) in &shim.env {
        lines.push(format!("$env:{} = {}", key, powershell_literal(value)));
    }

    // Add working directory change if specified
    if let Some(ref dir) = shim.working_dir {
        lines.push(format!(
            "Set-Location -LiteralPath {}",
            powershell_literal(&dir.display().to_string())
        ));
    }

    // Build the command
    let mut cmd_parts = vec![powershell_literal(&shim.target.display().to_string())];
    cmd_parts.extend(shim.args.iter().map(|arg| powershell_literal(arg)));
    cmd_parts.push("$args".to_string());

    lines.push(format!("& {}", cmd_parts.join(" ")));

    // Propagate the exit code of the wrapped command to our caller
    lines.push("exit $LASTEXITCODE".to_string());

    lines.join("\n")
}

/// Generate Unix shell script content
///
/// Target paths are emitted with forward slashes so the same script also works
/// from Git Bash / MSYS2 on Windows, where `Path::display()` would otherwise
/// produce backslashes that a POSIX shell treats as escapes.
pub(crate) fn shell(shim: &Shim) -> String {
    let mut lines = vec!["#!/bin/sh".to_string(), marker_line(ShimType::Shell)];

    // Add environment variables
    for (key, value) in &shim.env {
        lines.push(format!("{}={}", key, shell_literal(value)));
        lines.push(format!("export {}", key));
    }

    // Add working directory change if specified
    if let Some(ref dir) = shim.working_dir {
        lines.push(format!("cd {}", shell_path(&dir.display().to_string())));
    }

    // Build the command
    let mut cmd_parts = vec![shell_path(
        &shim.target.display().to_string().replace('\\', "/"),
    )];
    cmd_parts.extend(shim.args.iter().map(|arg| shell_argument(arg)));
    cmd_parts.push("\"$@\"".to_string());

    // `exec` replaces this process, so the exit code needs no handling
    lines.push(format!("exec {}", cmd_parts.join(" ")));

    lines.join("\n")
}
