# Node.js Plugin Configuration
# This file defines how vx manages Node.js and npm

[metadata]
name = "node"
version = "1.0.0"
description = "Node.js JavaScript runtime and npm package manager"
author = "vx team"
homepage = "https://nodejs.org"
repository = "https://github.com/nodejs/node"
license = "MIT"
keywords = ["node", "nodejs", "javascript", "npm", "runtime"]

# Version definitions
[versions.latest]
version = "21.6.0"
is_lts = false
is_latest = true
download_sources = ["nodejs_official", "nodejs_mirror"]

[versions.lts]
version = "20.11.0"
is_lts = true
is_latest = false
download_sources = ["nodejs_official", "nodejs_mirror"]

[versions."20.11.0"]
version = "20.11.0"
release_date = "2024-01-09"
is_lts = true
is_latest = false
download_sources = ["nodejs_official", "nodejs_mirror"]

[versions."21.6.0"]
version = "21.6.0"
release_date = "2024-01-14"
is_lts = false
is_latest = true
download_sources = ["nodejs_official", "nodejs_mirror"]

[versions."18.19.0"]
version = "18.19.0"
release_date = "2024-01-09"
is_lts = true
is_latest = false
download_sources = ["nodejs_official", "nodejs_mirror"]

# Download sources configuration
[download_sources.nodejs_official]
name = "Node.js Official"
platform = "all"
arch = "x64"
url_template = "https://nodejs.org/dist/v{version}/node-v{version}-{platform}-{arch}.{ext}"
checksum_url = "https://nodejs.org/dist/v{version}/SHASUMS256.txt"
signature_url = "https://nodejs.org/dist/v{version}/SHASUMS256.txt.sig"

[download_sources.nodejs_mirror]
name = "Node.js Mirror (China)"
platform = "all"
arch = "x64"
url_template = "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/v{version}/node-v{version}-{platform}-{arch}.{ext}"
checksum_url = "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/v{version}/SHASUMS256.txt"

[download_sources.homebrew]
name = "Homebrew"
platform = "macos"
arch = "all"
url_template = "brew://node"

[download_sources.chocolatey]
name = "Chocolatey"
platform = "windows"
arch = "all"
url_template = "choco://nodejs"

# Installation methods
[install_methods.archive_windows]
name = "Archive Extraction (Windows)"
method_type = "archive"
platform = "windows"
commands = ["extract_zip"]
post_install = ["add_to_path", "verify_npm"]

[install_methods.archive_unix]
name = "Archive Extraction (Unix)"
method_type = "archive"
platform = "unix"
commands = ["extract_tar_xz"]
post_install = ["create_symlinks", "add_to_path", "verify_npm"]

[install_methods.package_manager_brew]
name = "Homebrew Package Manager"
method_type = "package_manager"
platform = "macos"
commands = ["brew install node"]

[install_methods.package_manager_choco]
name = "Chocolatey Package Manager"
method_type = "package_manager"
platform = "windows"
commands = ["choco install nodejs"]

[install_methods.nvm_installer]
name = "Node Version Manager"
method_type = "script"
platform = "unix"
commands = ["curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"]
post_install = ["source ~/.bashrc", "nvm install {version}", "nvm use {version}"]

# Registry configurations
[registries.official]
name = "Official Node.js"
base_url = "https://nodejs.org/dist"
api_url = "https://nodejs.org/dist/index.json"
priority = 100

[registries.mirror_china]
name = "China Mirror"
base_url = "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release"
priority = 80

[registries.mirror_taobao]
name = "Taobao Mirror"
base_url = "https://npm.taobao.org/mirrors/node"
priority = 75
