# provider.star - Jujutsu (jj) provider
#
# jj: A Git-compatible DVCS that is both simple and powerful
# Releases: https://github.com/jj-vcs/jj/releases
# Asset format: jj-{vversion}-{triple}.{ext}
# Tag format:   v{version}
#
# Uses github_rust_provider — standard Rust triple naming with v-prefix in asset.

load("@vx//stdlib:provider.star",
     "github_rust_provider", "runtime_def", "github_permissions", "dep_def")

# ---------------------------------------------------------------------------
# Provider metadata
# ---------------------------------------------------------------------------
name        = "jj"
description = "Jujutsu (jj) - A Git-compatible DVCS that is both simple and powerful"
homepage    = "https://github.com/jj-vcs/jj"
repository  = "https://github.com/jj-vcs/jj"
license     = "Apache-2.0"
ecosystem   = "devtools"
aliases     = ["jujutsu"]

# ---------------------------------------------------------------------------
# Runtime definitions
# ---------------------------------------------------------------------------

runtimes = [runtime_def("jj", aliases=["jujutsu"],
                         version_pattern="jj \\d+")]

# ---------------------------------------------------------------------------
# Permissions
# ---------------------------------------------------------------------------

permissions = github_permissions()

# ---------------------------------------------------------------------------
# Provider functions — all generated by github_rust_provider
#
# jj asset: "jj-{vversion}-{triple}.{ext}"
# jj has no strip_prefix (executable at archive root)
# ---------------------------------------------------------------------------

_p = github_rust_provider(
    "jj-vcs", "jj",
    asset      = "jj-{vversion}-{triple}.{ext}",
    executable = "jj",
)

fetch_versions   = _p["fetch_versions"]
download_url     = _p["download_url"]
install_layout   = _p["install_layout"]
store_root       = _p["store_root"]
get_execute_path = _p["get_execute_path"]
post_install     = _p["post_install"]
environment      = _p["environment"]

# ---------------------------------------------------------------------------
# deps — recommends git
# ---------------------------------------------------------------------------

def deps(_ctx, _version):
    return [dep_def("git", version=">=2.41", optional=True,
                    reason="jj uses git as backend for version control")]

# ---------------------------------------------------------------------------
# constraints — runtime recommendations
# ---------------------------------------------------------------------------

constraints = [
    {
        "when":       "*",
        "recommends": [
            {
                "runtime": "git",
                "version": ">=2.41",
                "reason":  "jj uses git as backend for version control",
            },
        ],
    },
]
