//! Build script for vx-cli
//!
//! This script:
//! 1. Collects all `provider.star` manifests at compile time and embeds them
//!    into the binary (RFC 0013: Manifest-Driven Provider Registration)
//! 2. On Windows, locates and embeds bridge binaries (e.g., `MSBuild.exe`)
//!    so they can be deployed without shipping separate files

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use vx_star_metadata::StarMetadata;

fn main() {
    embed_provider_manifests();
    embed_bridge_binaries();
}

fn embed_provider_manifests() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("provider_manifests.rs");
    // The combined TOML file that will be embedded via include_str!
    let combined_toml_path = Path::new(&out_dir).join("all_providers.toml");

    // Find the vx-providers directory relative to this crate
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let providers_dir = Path::new(&manifest_dir).join("../vx-providers");

    let mut manifests: Vec<(String, String)> = Vec::new();

    if providers_dir.exists()
        && let Ok(entries) = fs::read_dir(&providers_dir)
    {
        for entry in entries.flatten() {
            let provider_dir = entry.path();
            if !provider_dir.is_dir() {
                continue;
            }

            let dir_name = provider_dir
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("unknown")
                .to_string();

            // Load provider.star: extract metadata and generate minimal TOML
            let star_path = provider_dir.join("provider.star");
            if star_path.exists()
                && let Ok(content) = fs::read_to_string(&star_path)
                && let Some(toml) = extract_manifest_from_star(&dir_name, &content)
            {
                manifests.push((dir_name, toml));
            }
        }
    }

    // Sort manifests by name for deterministic output
    manifests.sort_by(|a, b| a.0.cmp(&b.0));

    // -------------------------------------------------------------------------
    // Write the combined TOML file
    //
    // Format: each provider is separated by a TOML comment line:
    //   # ===PROVIDER:<name>===
    // TOML comments are ignored by the TOML parser, so this delimiter is safe.
    // -------------------------------------------------------------------------
    let mut combined = String::new();
    combined.push_str("# Auto-generated combined provider manifests\n");
    combined.push_str("# Generated by build.rs at compile time - DO NOT EDIT\n\n");

    for (name, content) in &manifests {
        combined.push_str(&format!("# ===PROVIDER:{}===\n", name));
        combined.push_str(content.trim());
        combined.push_str("\n\n");
    }

    fs::write(&combined_toml_path, &combined).unwrap();

    // -------------------------------------------------------------------------
    // Generate the Rust glue code — minimal: just the include_str! path and
    // the provider count.  All parsing logic lives in registry.rs directly,
    // so there is nothing to "generate" here.
    // -------------------------------------------------------------------------
    let combined_toml_path_escaped = combined_toml_path
        .display()
        .to_string()
        .replace('\\', "\\\\");

    let count = manifests.len();

    // Keep the generated file small and readable — no generated functions.
    let code = format!(
        concat!(
            "// Auto-generated by build.rs — DO NOT EDIT\n",
            "pub(crate) static ALL_PROVIDERS_TOML: &str = include_str!(\"{path}\");\n",
            "pub(crate) const PROVIDER_COUNT: usize = {count};\n",
        ),
        path = combined_toml_path_escaped,
        count = count,
    );

    fs::write(&dest_path, code).unwrap();
    // Tell Cargo to rerun this script if any provider file changes
    if providers_dir.exists() {
        println!("cargo:rerun-if-changed={}", providers_dir.display());
        if let Ok(entries) = fs::read_dir(&providers_dir) {
            for entry in entries.flatten() {
                let dir = entry.path();
                let star_path = dir.join("provider.star");
                if star_path.exists() {
                    println!("cargo:rerun-if-changed={}", star_path.display());
                }
            }
        }
    }

    // -------------------------------------------------------------------------
    // Generate provider_stars.rs — embeds all provider.star files so that
    // ProviderHandle can be registered at startup without filesystem access.
    //
    // Format: a static array of (name, star_content) pairs.
    // -------------------------------------------------------------------------
    embed_provider_stars(&out_dir, &providers_dir);
}

fn embed_provider_stars(out_dir: &str, providers_dir: &Path) {
    let dest_path = Path::new(out_dir).join("provider_stars.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();

    if providers_dir.exists()
        && let Ok(dir_entries) = fs::read_dir(providers_dir)
    {
        for entry in dir_entries.flatten() {
            let provider_dir = entry.path();
            if !provider_dir.is_dir() {
                continue;
            }
            let star_path = provider_dir.join("provider.star");
            if star_path.exists() {
                let dir_name = provider_dir
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("unknown")
                    .to_string();
                entries.push((dir_name, star_path));
            }
        }
    }

    // Sort for deterministic output
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — DO NOT EDIT\n");
    code.push_str("// Embedded provider.star contents for ProviderHandle registration\n\n");

    // Generate individual constants
    for (name, star_path) in &entries {
        let const_name = name.to_uppercase().replace('-', "_");
        let path_escaped = star_path.display().to_string().replace('\\', "\\\\");
        code.push_str(&format!(
            "pub(crate) static PROVIDER_STAR_{}: &str = include_str!(\"{}\");\n",
            const_name, path_escaped
        ));
    }

    code.push('\n');

    // Generate the combined array
    code.push_str("/// All embedded provider.star contents: `(provider_name, star_content)`\n");
    code.push_str("pub(crate) static ALL_PROVIDER_STARS: &[(&str, &str)] = &[\n");
    for (name, _) in &entries {
        let const_name = name.to_uppercase().replace('-', "_");
        code.push_str(&format!(
            "    (\"{}\", PROVIDER_STAR_{}),\n",
            name, const_name
        ));
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).unwrap();
}

/// Extract provider metadata from a Starlark provider.star file and generate
/// a minimal TOML manifest compatible with ProviderManifest::parse().
///
/// Parses the following patterns from the Starlark script:
/// - `name = "xxx"` → provider name (direct assignment)
/// - `description = "xxx"` → provider description
/// - `ecosystem = "xxx"` → provider ecosystem
/// - `homepage = "xxx"` → provider homepage
/// - `runtimes = [runtime_def("xxx", ...), bundled_runtime_def("xxx", "parent", ...)]`
/// - `platforms = {"os": [...]}` → platform constraints
fn extract_manifest_from_star(dir_name: &str, content: &str) -> Option<String> {
    let meta = StarMetadata::parse(content);
    let provider_name = meta.name_or(dir_name).to_string();
    let description = meta.description.unwrap_or_default();
    let ecosystem = meta.ecosystem.unwrap_or_default();
    let homepage = meta.homepage;
    let runtimes = meta.runtimes;
    let platform_os = meta.platforms;

    // Build minimal TOML
    let mut toml = String::new();
    toml.push_str("[provider]\n");
    toml.push_str(&format!(
        "name = \"{}\"\n",
        escape_toml_string(&provider_name)
    ));
    if !description.is_empty() {
        toml.push_str(&format!(
            "description = \"{}\"\n",
            escape_toml_string(&description)
        ));
    }
    if !ecosystem.is_empty() {
        toml.push_str(&format!(
            "ecosystem = \"{}\"\n",
            escape_toml_string(&ecosystem)
        ));
    }
    if let Some(ref hp) = homepage {
        toml.push_str(&format!("homepage = \"{}\"\n", escape_toml_string(hp)));
    }

    // Platform constraints at provider level
    if let Some(ref os_list) = platform_os {
        toml.push_str("\n[provider.platforms]\n");
        let os_values: Vec<String> = os_list.iter().map(|s| format!("\"{}\"", s)).collect();
        toml.push_str(&format!("os = [{}]\n", os_values.join(", ")));
    }

    // Runtime definitions
    if runtimes.is_empty() {
        // Fallback: create a single runtime with the provider name
        toml.push_str("\n[[runtimes]]\n");
        toml.push_str(&format!(
            "name = \"{}\"\n",
            escape_toml_string(&provider_name)
        ));
        toml.push_str(&format!(
            "executable = \"{}\"\n",
            escape_toml_string(&provider_name)
        ));
    } else {
        for rt in &runtimes {
            toml.push_str("\n[[runtimes]]\n");
            let rt_name = rt.name.as_deref().unwrap_or(&provider_name);
            let rt_executable = rt.executable.as_deref().unwrap_or(rt_name);
            toml.push_str(&format!("name = \"{}\"\n", escape_toml_string(rt_name)));
            toml.push_str(&format!(
                "executable = \"{}\"\n",
                escape_toml_string(rt_executable)
            ));
            if let Some(desc) = rt.description.as_deref()
                && !desc.is_empty()
            {
                toml.push_str(&format!("description = \"{}\"\n", escape_toml_string(desc)));
            }
            if !rt.aliases.is_empty() {
                let alias_values: Vec<String> =
                    rt.aliases.iter().map(|s| format!("\"{}\"", s)).collect();
                toml.push_str(&format!("aliases = [{}]\n", alias_values.join(", ")));
            }
            if let Some(priority) = rt.priority
                && priority != 100
            {
                toml.push_str(&format!("priority = {}\n", priority));
            }
        }
    }

    Some(toml)
}

/// Escape a string for use in TOML double-quoted strings
fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Embed bridge binaries (Windows only).
///
/// On Windows, we embed `MSBuild.exe` (from `vx-msbuild-bridge`) directly into
/// the `vx` binary. This is done by searching the cargo target directory for the
/// compiled bridge binary and generating `include_bytes!` code.
///
/// For non-Windows targets, an empty byte slice is embedded instead.
fn embed_bridge_binaries() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_bridges.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated embedded bridge binaries\n");
    code.push_str("// Generated by build.rs at compile time\n\n");

    // Only embed on Windows targets
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "windows" {
        if let Some(bridge_path) = find_msbuild_bridge() {
            // Use include_bytes! to embed the bridge binary
            let bridge_path_escaped = bridge_path.display().to_string().replace('\\', "\\\\");
            code.push_str(&format!(
                "/// Embedded MSBuild bridge binary (compiled from vx-msbuild-bridge)\n\
                 pub static MSBUILD_BRIDGE_BYTES: &[u8] = include_bytes!(\"{}\");\n",
                bridge_path_escaped
            ));
            println!("cargo:rerun-if-changed={}", bridge_path.display());
            eprintln!(
                "cargo:warning=Embedding MSBuild bridge from: {}",
                bridge_path.display()
            );
        } else {
            code.push_str(
                "/// MSBuild bridge binary not found at build time — will use filesystem fallback\n\
                 pub static MSBUILD_BRIDGE_BYTES: &[u8] = &[];\n",
            );
            eprintln!(
                "cargo:warning=MSBuild bridge binary not found, embedding empty placeholder. Build vx-msbuild-bridge first: cargo build -p vx-msbuild-bridge"
            );
        }
    } else {
        code.push_str(
            "/// MSBuild bridge is Windows-only\n\
             pub static MSBUILD_BRIDGE_BYTES: &[u8] = &[];\n",
        );
    }

    fs::write(&dest_path, code).unwrap();
}

/// Search for the compiled MSBuild bridge binary in the target directory.
///
/// We search both release and debug profiles, preferring the same profile
/// as the current build.
fn find_msbuild_bridge() -> Option<PathBuf> {
    let out_dir = env::var("OUT_DIR").ok()?;

    // OUT_DIR is something like: target/<profile>/build/vx-cli-<hash>/out
    // We need to navigate up to the target/<profile> directory
    let out_path = PathBuf::from(&out_dir);

    // Walk up to find the target directory
    // OUT_DIR = <target_dir>/<profile>/build/<crate>-<hash>/out
    let target_profile_dir = out_path.parent()?.parent()?.parent()?;
    let target_dir = target_profile_dir.parent()?;

    let bridge_name = "MSBuild.exe";

    // Try current profile first
    let current_profile_candidate = target_profile_dir.join(bridge_name);
    if current_profile_candidate.exists() {
        return Some(current_profile_candidate);
    }

    // Try release profile
    let release_candidate = target_dir.join("release").join(bridge_name);
    if release_candidate.exists() {
        return Some(release_candidate);
    }

    // Try debug profile
    let debug_candidate = target_dir.join("debug").join(bridge_name);
    if debug_candidate.exists() {
        return Some(debug_candidate);
    }

    None
}
