# provider.star - prek provider
#
# prek: Better pre-commit, re-engineered in Rust
# Releases: https://github.com/j178/prek/releases
# Asset format: prek-{triple}.{ext}
# Tag format:   v{version}
#
# Uses github_rust_provider — standard Rust triple naming, no version in asset.

load("@vx//stdlib:provider.star",
     "github_rust_provider", "runtime_def", "github_permissions", "dep_def")

# ---------------------------------------------------------------------------
# Provider metadata
# ---------------------------------------------------------------------------
name        = "prek"
description = "Better pre-commit, re-engineered in Rust"
homepage    = "https://prek.j178.dev"
repository  = "https://github.com/j178/prek"
license     = "MIT"
ecosystem   = "devtools"

# ---------------------------------------------------------------------------
# Runtime definitions
# ---------------------------------------------------------------------------

runtimes = [runtime_def("prek")]

# ---------------------------------------------------------------------------
# Permissions
# ---------------------------------------------------------------------------

permissions = github_permissions()

# ---------------------------------------------------------------------------
# Provider functions — all generated by github_rust_provider
#
# prek asset: "prek-{triple}.{ext}"  (no version in asset name)
# prek tag:   "v{version}"
# ---------------------------------------------------------------------------

_p = github_rust_provider(
    "j178", "prek",
    asset      = "prek-{triple}.{ext}",
    executable = "prek",
)

fetch_versions   = _p["fetch_versions"]
download_url     = _p["download_url"]
install_layout   = _p["install_layout"]
store_root       = _p["store_root"]
get_execute_path = _p["get_execute_path"]
post_install     = _p["post_install"]
environment      = _p["environment"]

# ---------------------------------------------------------------------------
# deps — requires git
# ---------------------------------------------------------------------------

def deps(_ctx, _version):
    return [dep_def("git", reason="Git is required by prek to install and run pre-commit hooks")]
