name: Simple Release

on:
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force create a release'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  simple-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run release-please (simple)
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          package-name: vx
          token: ${{ secrets.GITHUB_TOKEN }}
          include-v-in-tag: true

      - name: Debug outputs
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "PR: ${{ steps.release.outputs.pr }}"

  build-on-release:
    runs-on: ubuntu-latest
    needs: simple-release
    if: ${{ needs.simple-release.outputs.release_created == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/vx*
          tag_name: ${{ needs.simple-release.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
