name: Winget

# Publishes vx to Windows Package Manager (winget)
# Triggered when a release is published

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout winget-pkgs repository
        uses: actions/checkout@v4
        with:
          repository: loonghao/winget-pkgs
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "vx-bot"
          git config user.email "release@vx.dev"

      - name: Add Microsoft winget-pkgs as upstream
        run: |
          git remote add microsoft https://github.com/microsoft/winget-pkgs
          git pull --rebase microsoft master
          git push -f origin master

      - name: Publish to winget
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: loonghao.vx
          max-versions-to-keep: 5
          token: ${{ secrets.GITHUB_TOKEN }}
